# Generated by Django 4.1.2 on 2023-06-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0018_driver_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver_detail",
            name="d_photo",
            field=models.ImageField(
                blank=True,
                default="images/None/No0img.jpg",
                max_length=255,
                null=True,
                upload_to="driversphoto",
            ),
        ),
    ]
